const LANG = {
  it: {
    infoTitle: "Altre informazioni",
    size: "Dimensioni",
    colorModel: "Modello di colore",
    dctTitle: "Coefficienti DCT del blocco:",
    quantTitle: "Tabella di Quantizzazione",
    blockSelected: "Blocco selezionato",
    errorDCT: "Errore: impossibile ottenere i coefficienti DCT per il blocco selezionato.",
    errorLoad: "Errore durante il caricamento dell'immagine",
    errorLoadTimeout: "Errore durante il caricamento dell'immagine (timeout). Per favore, riprova.",
    errorNotJPEG: "Il file caricato non è un JPEG valido.",
    errorTestImage: "Errore durante il caricamento dell'immagine di test.",
    errorNoImage: "Carica un'immagine o seleziona un'immagine di test prima di procedere.",
    errorWasm: "Errore: il modulo WebAssembly non è pronto.",
    errorDecoder: "Impossibile inizializzare il decoder.",
    errorAnalysis: "Errore durante l'analisi del file JPEG.",
    clickBlock: "Clicca su un blocco per visualizzare i coefficienti DCT",
    original: "Originale",
    componentY: "Componente Y",
    componentCb: "Componente Cb",
    componentCr: "Componente Cr",
    selectTestImage: "Seleziona un'immagine di test:",
    uploadImage: "Carica un'immagine JPEG:",
    dctAndQuant: "DCT & Quantizzazione",
    components: "Componenti",
    fullAnalysis: "Analisi completa",
    reset: "Reset",
    backToTop: "Torna su",
    errorAlreadyAnalyzing: "Errore: Analisi già in corso. Attendi il completamento prima di avviarne una nuova.",
  },
  en: {
    infoTitle: "Other information",
    size: "Size",
    colorModel: "Color model",
    dctTitle: "Block DCT coefficients:",
    quantTitle: "Quantization Table",
    blockSelected: "Selected block",
    errorDCT: "Error: unable to get DCT coefficients for the selected block.",
    errorLoad: "Error loading image.",
    errorLoadTimeout: "Error loading image (timeout). Please try again.",
    errorNotJPEG: "The uploaded file is not a valid JPEG.",
    errorTestImage: "Error loading test image.",
    errorNoImage: "Upload an image or select a test image before proceeding.",
    errorWasm: "Error: WebAssembly module is not ready.",
    errorDecoder: "Unable to initialize decoder.",
    errorAnalysis: "Error analyzing JPEG file.",
    clickBlock: "Click on a block to view the DCT coefficients",
    original: "Original",
    componentY: "Component Y",
    componentCb: "Component Cb",
    componentCr: "Component Cr",
    selectTestImage: "Select a test image:",
    uploadImage: "Upload a JPEG image:",
    dctAndQuant: "DCT & Quantization",
    components: "Components",
    fullAnalysis: "Full Analysis",
    reset: "Reset",
    backToTop: "Back to top",
    errorAlreadyAnalyzing: "Error: Analysis already in progress. Please wait for it to complete before starting a new one.",
  }
};